### ISSUE TITLE
Your game js

### ISSUE THREAD

**Issue by Israelpatnem** [evgeniikucheriavii/JS-Game#1]
I download your js games - cars. After 5-10 seconds, car is disappear. It's really problem, because car after disappear is continue to move

**Comment by evgeniikucheriavii** [comment]
Hello! The game worked well the last time I tested it. Perhaps I forgot to commit final fixes. I will check everything as soon as I can.

**Comment by evgeniikucheriavii** [comment]
Hello again! I updated the code, now everything should be alright. It'll be nice if you test it and leave your feedback.

**Comment by Israelpatnem** [comment]
Ok. It's work good, but why in archive have a 2 html file?

**Comment by evgeniikucheriavii** [comment]
The game itself is in the game.html file now. It is embedded to index.html with iframe tag. It allows to select preferred width and height easily.

**Comment by evgeniikucheriavii** [comment]
I made the last fix - now no black space will be shown, if you open game.html on big screen.
